displayName=CARoadmap
author=IzdarT
description=Generate a Combat Achievement recommendations based on your player stats and boss kill counts!
tags=combat achievements, roadmap, progression, tier, CA
plugins=com.caroadmap.CARoadmapPlugin
version=v1.0.0
build=standard